apiVersion: v1
kind: Service
metadata:
  name: gitea-mysql
  namespace: default
spec:
  ports:
  - port: 3306
  selector:
    app: gitea-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-mysql
  namespace: default
spec:
  selector:
    matchLabels:
      app: gitea-mysql
  template:
    metadata:
      labels:
        app: gitea-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "gitea-root-password"
        - name: MYSQL_DATABASE
          value: "gitea"
        - name: MYSQL_USER
          value: "gitea"
        - name: MYSQL_PASSWORD
          value: "gitea-password"